# UNI: jjl2245, me2680
"""A test script to learn how to read ark files that have been generated by kaldi scripts"""

import kaldiio

root_path = '../../features/mfcc_pitch/'
lang = 'BN' #"BN" "EN" "ES" "FR" "JV" "KR" "MD" "RS" "TR"
file_name = 'raw_mfcc_pitch_test.1.ark'

for key, numpy_array in kaldiio.load_ark(root_path + lang + '/' + file_name): # For each line of the ark file
    print("File identifier:", key)  # This is the corresponding wav file
    print("Features shape:", numpy_array.shape) # Print out the matrix shape
    print("Feature embedding:", numpy_array) # Read a portion of the ark file into a numpy array